/* CVS $Id: $ */
package vocabs; 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from prov.rdf 
 * @author Auto-generated by schemagen on 02 May 2016 23:35 
 */
public class PROV {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/ns/prov#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "Working Group Note version 2013-04-30";
    
    public static final Model getSchema() { return m_model; }
    /** <p>An object property to express the accountability of an agent towards another 
     *  agent. The subordinate agent acted on behalf of the responsible agent in an 
     *  actual activity.</p>
     */
    public static final Property ACTED_ON_BEHALF_OF = m_model.createProperty( "http://www.w3.org/ns/prov#actedOnBehalfOf" );
    
    public static final Property ACTIVITY = m_model.createProperty( "http://www.w3.org/ns/prov#activity" );
    
    public static final Property AGENT = m_model.createProperty( "http://www.w3.org/ns/prov#agent" );
    
    public static final Property ALTERNATE_OF = m_model.createProperty( "http://www.w3.org/ns/prov#alternateOf" );
    
    /** <p>prov:asInBundle is used to specify which bundle the general entity of a prov:mentionOf 
     *  property is described. When :x prov:mentionOf :y and :y is described in Bundle 
     *  :b, the triple :x prov:asInBundle :b is also asserted to cite the Bundle in 
     *  which :y was described.</p>
     */
    public static final Property AS_IN_BUNDLE = m_model.createProperty( "http://www.w3.org/ns/prov#asInBundle" );
    
    /** <p>The Location of any resource.This property has multiple RDFS domains to suit 
     *  multiple OWL Profiles. See &lt;a href="#owl-profile"&gt;PROV-O OWL Profile&lt;/a&gt;.</p>
     */
    public static final Property AT_LOCATION = m_model.createProperty( "http://www.w3.org/ns/prov#atLocation" );
    
    /** <p>The time at which an InstantaneousEvent occurred, in the form of xsd:dateTime.</p> */
    public static final Property AT_TIME = m_model.createProperty( "http://www.w3.org/ns/prov#atTime" );
    
    public static final Property DERIVED_BY_INSERTION_FROM = m_model.createProperty( "http://www.w3.org/ns/prov#derivedByInsertionFrom" );
    
    public static final Property DERIVED_BY_REMOVAL_FROM = m_model.createProperty( "http://www.w3.org/ns/prov#derivedByRemovalFrom" );
    
    /** <p>relates a generic provenance query service resource (type prov:ServiceDescription) 
     *  to a specific query service description (e.g. a prov:DirectQueryService or 
     *  a sd:Service).</p>
     */
    public static final Property DESCRIBES_SERVICE = m_model.createProperty( "http://www.w3.org/ns/prov#describesService" );
    
    public static final Property DICTIONARY = m_model.createProperty( "http://www.w3.org/ns/prov#dictionary" );
    
    /** <p>The time at which an activity ended. See also prov:startedAtTime.</p> */
    public static final Property ENDED_AT_TIME = m_model.createProperty( "http://www.w3.org/ns/prov#endedAtTime" );
    
    public static final Property ENTITY = m_model.createProperty( "http://www.w3.org/ns/prov#entity" );
    
    public static final Property GENERATED = m_model.createProperty( "http://www.w3.org/ns/prov#generated" );
    
    /** <p>The time at which an entity was completely created and is available for use.</p> */
    public static final Property GENERATED_AT_TIME = m_model.createProperty( "http://www.w3.org/ns/prov#generatedAtTime" );
    
    /** <p>This property has multiple RDFS domains to suit multiple OWL Profiles. See 
     *  &lt;a href="#owl-profile"&gt;PROV-O OWL Profile&lt;/a&gt;.The _optional_ Activity 
     *  of an Influence, which used, generated, invalidated, or was the responsibility 
     *  of some Entity. This property is _not_ used by ActivityInfluence (use prov:activity 
     *  instead).</p>
     */
    public static final Property HAD_ACTIVITY = m_model.createProperty( "http://www.w3.org/ns/prov#hadActivity" );
    
    public static final Property HAD_DICTIONARY_MEMBER = m_model.createProperty( "http://www.w3.org/ns/prov#hadDictionaryMember" );
    
    /** <p>The _optional_ Generation involved in an Entity's Derivation.</p> */
    public static final Property HAD_GENERATION = m_model.createProperty( "http://www.w3.org/ns/prov#hadGeneration" );
    
    public static final Property HAD_MEMBER = m_model.createProperty( "http://www.w3.org/ns/prov#hadMember" );
    
    /** <p>The _optional_ Plan adopted by an Agent in Association with some Activity. 
     *  Plan specifications are out of the scope of this specification.</p>
     */
    public static final Property HAD_PLAN = m_model.createProperty( "http://www.w3.org/ns/prov#hadPlan" );
    
    public static final Property HAD_PRIMARY_SOURCE = m_model.createProperty( "http://www.w3.org/ns/prov#hadPrimarySource" );
    
    /** <p>The _optional_ Role that an Entity assumed in the context of an Activity. 
     *  For example, :baking prov:used :spoon; prov:qualified [ a prov:Usage; prov:entity 
     *  :spoon; prov:hadRole roles:mixing_implement ].This property has multiple RDFS 
     *  domains to suit multiple OWL Profiles. See &lt;a href="#owl-profile"&gt;PROV-O 
     *  OWL Profile&lt;/a&gt;.</p>
     */
    public static final Property HAD_ROLE = m_model.createProperty( "http://www.w3.org/ns/prov#hadRole" );
    
    /** <p>The _optional_ Usage involved in an Entity's Derivation.</p> */
    public static final Property HAD_USAGE = m_model.createProperty( "http://www.w3.org/ns/prov#hadUsage" );
    
    /** <p>Indicates anchor URI for a potentially dynamic resource instance.</p> */
    public static final Property HAS_ANCHOR = m_model.createProperty( "http://www.w3.org/ns/prov#has_anchor" );
    
    /** <p>Indicates a provenance-URI for a resource; the resource identified by this 
     *  property presents a provenance record about its subject or anchor resource.</p>
     */
    public static final Property HAS_PROVENANCE = m_model.createProperty( "http://www.w3.org/ns/prov#has_provenance" );
    
    /** <p>Indicates a provenance query service that can access provenance related to 
     *  its subject or anchor resource.</p>
     */
    public static final Property HAS_QUERY_SERVICE = m_model.createProperty( "http://www.w3.org/ns/prov#has_query_service" );
    
    public static final Property INFLUENCED = m_model.createProperty( "http://www.w3.org/ns/prov#influenced" );
    
    /** <p>Subproperties of prov:influencer are used to cite the object of an unqualified 
     *  PROV-O triple whose predicate is a subproperty of prov:wasInfluencedBy (e.g. 
     *  prov:used, prov:wasGeneratedBy). prov:influencer is used much like rdf:object 
     *  is used.</p>
     */
    public static final Property INFLUENCER = m_model.createProperty( "http://www.w3.org/ns/prov#influencer" );
    
    public static final Property INSERTED_KEY_ENTITY_PAIR = m_model.createProperty( "http://www.w3.org/ns/prov#insertedKeyEntityPair" );
    
    public static final Property INVALIDATED = m_model.createProperty( "http://www.w3.org/ns/prov#invalidated" );
    
    /** <p>The time at which an entity was invalidated (i.e., no longer usable).</p> */
    public static final Property INVALIDATED_AT_TIME = m_model.createProperty( "http://www.w3.org/ns/prov#invalidatedAtTime" );
    
    /** <p>prov:mentionOf is used to specialize an entity as described in another bundle. 
     *  It is to be used in conjuction with prov:asInBundle. prov:asInBundle is used 
     *  to cite the Bundle in which the generalization was mentioned.</p>
     */
    public static final Property MENTION_OF = m_model.createProperty( "http://www.w3.org/ns/prov#mentionOf" );
    
    public static final Property PAIR_ENTITY = m_model.createProperty( "http://www.w3.org/ns/prov#pairEntity" );
    
    public static final Property PAIR_KEY = m_model.createProperty( "http://www.w3.org/ns/prov#pairKey" );
    
    /** <p>Relates a resource to a provenance pingback service that may receive additional 
     *  provenance links about the resource.</p>
     */
    public static final Property PINGBACK = m_model.createProperty( "http://www.w3.org/ns/prov#pingback" );
    
    /** <p>Relates a provenance service to a URI template string for constructing provenance-URIs.</p> */
    public static final Property PROVENANCE_URI_TEMPLATE = m_model.createProperty( "http://www.w3.org/ns/prov#provenanceUriTemplate" );
    
    /** <p>If this Activity prov:wasAssociatedWith Agent :ag, then it can qualify the 
     *  Association using prov:qualifiedAssociation [ a prov:Association; prov:agent 
     *  :ag; :foo :bar ].</p>
     */
    public static final Property QUALIFIED_ASSOCIATION = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedAssociation" );
    
    /** <p>If this Entity prov:wasAttributedTo Agent :ag, then it can qualify how it 
     *  was influenced using prov:qualifiedAttribution [ a prov:Attribution; prov:agent 
     *  :ag; :foo :bar ].</p>
     */
    public static final Property QUALIFIED_ATTRIBUTION = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedAttribution" );
    
    /** <p>If this Activity prov:wasInformedBy Activity :a, then it can qualify how it 
     *  was influenced using prov:qualifiedCommunication [ a prov:Communication; prov:activity 
     *  :a; :foo :bar ].</p>
     */
    public static final Property QUALIFIED_COMMUNICATION = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedCommunication" );
    
    /** <p>If this Agent prov:actedOnBehalfOf Agent :ag, then it can qualify how with 
     *  prov:qualifiedResponsibility [ a prov:Responsibility; prov:agent :ag; :foo 
     *  :bar ].</p>
     */
    public static final Property QUALIFIED_DELEGATION = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedDelegation" );
    
    /** <p>If this Entity prov:wasDerivedFrom Entity :e, then it can qualify how it was 
     *  derived using prov:qualifiedDerivation [ a prov:Derivation; prov:entity :e; 
     *  :foo :bar ].</p>
     */
    public static final Property QUALIFIED_DERIVATION = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedDerivation" );
    
    /** <p>If this Activity prov:wasEndedBy Entity :e1, then it can qualify how it was 
     *  ended using prov:qualifiedEnd [ a prov:End; prov:entity :e1; :foo :bar ].</p>
     */
    public static final Property QUALIFIED_END = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedEnd" );
    
    /** <p>If this Activity prov:generated Entity :e, then it can qualify how it performed 
     *  the Generation using prov:qualifiedGeneration [ a prov:Generation; prov:entity 
     *  :e; :foo :bar ].</p>
     */
    public static final Property QUALIFIED_GENERATION = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedGeneration" );
    
    /** <p>Because prov:qualifiedInfluence is a broad relation, the more specific relations 
     *  (qualifiedCommunication, qualifiedDelegation, qualifiedEnd, etc.) should be 
     *  used when applicable.</p>
     */
    public static final Property QUALIFIED_INFLUENCE = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedInfluence" );
    
    public static final Property QUALIFIED_INSERTION = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedInsertion" );
    
    /** <p>If this Entity prov:wasInvalidatedBy Activity :a, then it can qualify how 
     *  it was invalidated using prov:qualifiedInvalidation [ a prov:Invalidation; 
     *  prov:activity :a; :foo :bar ].</p>
     */
    public static final Property QUALIFIED_INVALIDATION = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedInvalidation" );
    
    /** <p>If this Entity prov:hadPrimarySource Entity :e, then it can qualify how using 
     *  prov:qualifiedPrimarySource [ a prov:PrimarySource; prov:entity :e; :foo :bar 
     *  ].</p>
     */
    public static final Property QUALIFIED_PRIMARY_SOURCE = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedPrimarySource" );
    
    /** <p>If this Entity prov:wasQuotedFrom Entity :e, then it can qualify how using 
     *  prov:qualifiedQuotation [ a prov:Quotation; prov:entity :e; :foo :bar ].</p>
     */
    public static final Property QUALIFIED_QUOTATION = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedQuotation" );
    
    public static final Property QUALIFIED_REMOVAL = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedRemoval" );
    
    /** <p>If this Entity prov:wasRevisionOf Entity :e, then it can qualify how it was 
     *  revised using prov:qualifiedRevision [ a prov:Revision; prov:entity :e; :foo 
     *  :bar ].</p>
     */
    public static final Property QUALIFIED_REVISION = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedRevision" );
    
    /** <p>If this Activity prov:wasStartedBy Entity :e1, then it can qualify how it 
     *  was started using prov:qualifiedStart [ a prov:Start; prov:entity :e1; :foo 
     *  :bar ].</p>
     */
    public static final Property QUALIFIED_START = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedStart" );
    
    /** <p>If this Activity prov:used Entity :e, then it can qualify how it used it using 
     *  prov:qualifiedUsage [ a prov:Usage; prov:entity :e; :foo :bar ].</p>
     */
    public static final Property QUALIFIED_USAGE = m_model.createProperty( "http://www.w3.org/ns/prov#qualifiedUsage" );
    
    public static final Property REMOVED_KEY = m_model.createProperty( "http://www.w3.org/ns/prov#removedKey" );
    
    public static final Property SPECIALIZATION_OF = m_model.createProperty( "http://www.w3.org/ns/prov#specializationOf" );
    
    /** <p>The time at which an activity started. See also prov:endedAtTime.</p> */
    public static final Property STARTED_AT_TIME = m_model.createProperty( "http://www.w3.org/ns/prov#startedAtTime" );
    
    /** <p>A prov:Entity that was used by this prov:Activity. For example, :baking prov:used 
     *  :spoon, :egg, :oven .</p>
     */
    public static final Property USED = m_model.createProperty( "http://www.w3.org/ns/prov#used" );
    
    public static final Property VALUE = m_model.createProperty( "http://www.w3.org/ns/prov#value" );
    
    /** <p>An prov:Agent that had some (unspecified) responsibility for the occurrence 
     *  of this prov:Activity.</p>
     */
    public static final Property WAS_ASSOCIATED_WITH = m_model.createProperty( "http://www.w3.org/ns/prov#wasAssociatedWith" );
    
    /** <p>Attribution is the ascribing of an entity to an agent.</p> */
    public static final Property WAS_ATTRIBUTED_TO = m_model.createProperty( "http://www.w3.org/ns/prov#wasAttributedTo" );
    
    /** <p>The more specific subproperties of prov:wasDerivedFrom (i.e., prov:wasQuotedFrom, 
     *  prov:wasRevisionOf, prov:hadPrimarySource) should be used when applicable.</p>
     */
    public static final Property WAS_DERIVED_FROM = m_model.createProperty( "http://www.w3.org/ns/prov#wasDerivedFrom" );
    
    /** <p>End is when an activity is deemed to have ended. An end may refer to an entity, 
     *  known as trigger, that terminated the activity.</p>
     */
    public static final Property WAS_ENDED_BY = m_model.createProperty( "http://www.w3.org/ns/prov#wasEndedBy" );
    
    public static final Property WAS_GENERATED_BY = m_model.createProperty( "http://www.w3.org/ns/prov#wasGeneratedBy" );
    
    /** <p>This property has multiple RDFS domains to suit multiple OWL Profiles. See 
     *  &lt;a href="#owl-profile"&gt;PROV-O OWL Profile&lt;/a&gt;.Because prov:wasInfluencedBy 
     *  is a broad relation, its more specific subproperties (e.g. prov:wasInformedBy, 
     *  prov:actedOnBehalfOf, prov:wasEndedBy, etc.) should be used when applicable.</p>
     */
    public static final Property WAS_INFLUENCED_BY = m_model.createProperty( "http://www.w3.org/ns/prov#wasInfluencedBy" );
    
    /** <p>An activity a2 is dependent on or informed by another activity a1, by way 
     *  of some unspecified entity that is generated by a1 and used by a2.</p>
     */
    public static final Property WAS_INFORMED_BY = m_model.createProperty( "http://www.w3.org/ns/prov#wasInformedBy" );
    
    public static final Property WAS_INVALIDATED_BY = m_model.createProperty( "http://www.w3.org/ns/prov#wasInvalidatedBy" );
    
    /** <p>An entity is derived from an original entity by copying, or 'quoting', some 
     *  or all of it.</p>
     */
    public static final Property WAS_QUOTED_FROM = m_model.createProperty( "http://www.w3.org/ns/prov#wasQuotedFrom" );
    
    /** <p>A revision is a derivation that revises an entity into a revised version.</p> */
    public static final Property WAS_REVISION_OF = m_model.createProperty( "http://www.w3.org/ns/prov#wasRevisionOf" );
    
    /** <p>Start is when an activity is deemed to have started. A start may refer to 
     *  an entity, known as trigger, that initiated the activity.</p>
     */
    public static final Property WAS_STARTED_BY = m_model.createProperty( "http://www.w3.org/ns/prov#wasStartedBy" );
    
    public static final Resource ACCEPT = m_model.createResource( "http://www.w3.org/ns/prov#Accept" );
    
    public static final Resource ACTIVITY_CLASS = m_model.createResource( "http://www.w3.org/ns/prov#Activity" );
    
    /** <p>It is not recommended that the type ActivityInfluence be asserted without 
     *  also asserting one of its more specific subclasses.ActivityInfluence provides 
     *  additional descriptions of an Activity's binary influence upon any other kind 
     *  of resource. Instances of ActivityInfluence use the prov:activity property 
     *  to cite the influencing Activity.</p>
     */
    public static final Resource ACTIVITY_INFLUENCE = m_model.createResource( "http://www.w3.org/ns/prov#ActivityInfluence" );
    
    public static final Resource AGENT_CLASS = m_model.createResource( "http://www.w3.org/ns/prov#Agent" );
    
    /** <p>It is not recommended that the type AgentInfluence be asserted without also 
     *  asserting one of its more specific subclasses.AgentInfluence provides additional 
     *  descriptions of an Agent's binary influence upon any other kind of resource. 
     *  Instances of AgentInfluence use the prov:agent property to cite the influencing 
     *  Agent.</p>
     */
    public static final Resource AGENT_INFLUENCE = m_model.createResource( "http://www.w3.org/ns/prov#AgentInfluence" );
    
    /** <p>An instance of prov:Association provides additional descriptions about the 
     *  binary prov:wasAssociatedWith relation from an prov:Activity to some prov:Agent 
     *  that had some responsiblity for it. For example, :baking prov:wasAssociatedWith 
     *  :baker; prov:qualifiedAssociation [ a prov:Association; prov:agent :baker; 
     *  :foo :bar ].</p>
     */
    public static final Resource ASSOCIATION = m_model.createResource( "http://www.w3.org/ns/prov#Association" );
    
    /** <p>An instance of prov:Attribution provides additional descriptions about the 
     *  binary prov:wasAttributedTo relation from an prov:Entity to some prov:Agent 
     *  that had some responsible for it. For example, :cake prov:wasAttributedTo 
     *  :baker; prov:qualifiedAttribution [ a prov:Attribution; prov:entity :baker; 
     *  :foo :bar ].</p>
     */
    public static final Resource ATTRIBUTION = m_model.createResource( "http://www.w3.org/ns/prov#Attribution" );
    
    /** <p>Note that there are kinds of bundles (e.g. handwritten letters, audio recordings, 
     *  etc.) that are not expressed in PROV-O, but can be still be described by PROV-O.</p>
     */
    public static final Resource BUNDLE = m_model.createResource( "http://www.w3.org/ns/prov#Bundle" );
    
    public static final Resource COLLECTION = m_model.createResource( "http://www.w3.org/ns/prov#Collection" );
    
    /** <p>An instance of prov:Communication provides additional descriptions about the 
     *  binary prov:wasInformedBy relation from an informed prov:Activity to the prov:Activity 
     *  that informed it. For example, :you_jumping_off_bridge prov:wasInformedBy 
     *  :everyone_else_jumping_off_bridge; prov:qualifiedCommunication [ a prov:Communication; 
     *  prov:activity :everyone_else_jumping_off_bridge; :foo :bar ].</p>
     */
    public static final Resource COMMUNICATION = m_model.createResource( "http://www.w3.org/ns/prov#Communication" );
    
    public static final Resource CONTRIBUTE = m_model.createResource( "http://www.w3.org/ns/prov#Contribute" );
    
    public static final Resource CONTRIBUTOR = m_model.createResource( "http://www.w3.org/ns/prov#Contributor" );
    
    public static final Resource COPYRIGHT = m_model.createResource( "http://www.w3.org/ns/prov#Copyright" );
    
    public static final Resource CREATE = m_model.createResource( "http://www.w3.org/ns/prov#Create" );
    
    public static final Resource CREATOR = m_model.createResource( "http://www.w3.org/ns/prov#Creator" );
    
    /** <p>An instance of prov:Delegation provides additional descriptions about the 
     *  binary prov:actedOnBehalfOf relation from a performing prov:Agent to some 
     *  prov:Agent for whom it was performed. For example, :mixing prov:wasAssociatedWith 
     *  :toddler . :toddler prov:actedOnBehalfOf :mother; prov:qualifiedDelegation 
     *  [ a prov:Delegation; prov:entity :mother; :foo :bar ].</p>
     */
    public static final Resource DELEGATION = m_model.createResource( "http://www.w3.org/ns/prov#Delegation" );
    
    /** <p>An instance of prov:Derivation provides additional descriptions about the 
     *  binary prov:wasDerivedFrom relation from some derived prov:Entity to another 
     *  prov:Entity from which it was derived. For example, :chewed_bubble_gum prov:wasDerivedFrom 
     *  :unwrapped_bubble_gum; prov:qualifiedDerivation [ a prov:Derivation; prov:entity 
     *  :unwrapped_bubble_gum; :foo :bar ].The more specific forms of prov:Derivation 
     *  (i.e., prov:Revision, prov:Quotation, prov:PrimarySource) should be asserted 
     *  if they apply.</p>
     */
    public static final Resource DERIVATION = m_model.createResource( "http://www.w3.org/ns/prov#Derivation" );
    
    /** <p>This concept allows for the provenance of the dictionary, but also of its 
     *  constituents to be expressed. Such a notion of dictionary corresponds to a 
     *  wide variety of concrete data structures, such as a maps or associative arrays.A 
     *  given dictionary forms a given structure for its members. A different structure 
     *  (obtained either by insertion or removal of members) constitutes a different 
     *  dictionary.</p>
     */
    public static final Resource DICTIONARY_CLASS = m_model.createResource( "http://www.w3.org/ns/prov#Dictionary" );
    
    /** <p>Type for a generic provenance query service. Mainly for use in RDF provenance 
     *  query service descriptions, to facilitate discovery in linked data environments.</p>
     */
    public static final Resource DIRECT_QUERY_SERVICE = m_model.createResource( "http://www.w3.org/ns/prov#DirectQueryService" );
    
    public static final Resource EMPTY_COLLECTION = m_model.createResource( "http://www.w3.org/ns/prov#EmptyCollection" );
    
    public static final Resource EMPTY_DICTIONARY = m_model.createResource( "http://www.w3.org/ns/prov#EmptyDictionary" );
    
    /** <p>An instance of prov:End provides additional descriptions about the binary 
     *  prov:wasEndedBy relation from some ended prov:Activity to an prov:Entity that 
     *  ended it. For example, :ball_game prov:wasEndedBy :buzzer; prov:qualifiedEnd 
     *  [ a prov:End; prov:entity :buzzer; :foo :bar; prov:atTime '2012-03-09T08:05:08-05:00'^^xsd:dateTime 
     *  ].</p>
     */
    public static final Resource END = m_model.createResource( "http://www.w3.org/ns/prov#End" );
    
    public static final Resource ENTITY_CLASS = m_model.createResource( "http://www.w3.org/ns/prov#Entity" );
    
    /** <p>It is not recommended that the type EntityInfluence be asserted without also 
     *  asserting one of its more specific subclasses.EntityInfluence provides additional 
     *  descriptions of an Entity's binary influence upon any other kind of resource. 
     *  Instances of EntityInfluence use the prov:entity property to cite the influencing 
     *  Entity.</p>
     */
    public static final Resource ENTITY_INFLUENCE = m_model.createResource( "http://www.w3.org/ns/prov#EntityInfluence" );
    
    /** <p>An instance of prov:Generation provides additional descriptions about the 
     *  binary prov:wasGeneratedBy relation from a generated prov:Entity to the prov:Activity 
     *  that generated it. For example, :cake prov:wasGeneratedBy :baking; prov:qualifiedGeneration 
     *  [ a prov:Generation; prov:activity :baking; :foo :bar ].</p>
     */
    public static final Resource GENERATION = m_model.createResource( "http://www.w3.org/ns/prov#Generation" );
    
    /** <p>Because prov:Influence is a broad relation, its most specific subclasses (e.g. 
     *  prov:Communication, prov:Delegation, prov:End, prov:Revision, etc.) should 
     *  be used when applicable.An instance of prov:Influence provides additional 
     *  descriptions about the binary prov:wasInfluencedBy relation from some influenced 
     *  Activity, Entity, or Agent to the influencing Activity, Entity, or Agent. 
     *  For example, :stomach_ache prov:wasInfluencedBy :spoon; prov:qualifiedInfluence 
     *  [ a prov:Influence; prov:entity :spoon; :foo :bar ] . Because prov:Influence 
     *  is a broad relation, the more specific relations (Communication, Delegation, 
     *  End, etc.) should be used when applicable.</p>
     */
    public static final Resource INFLUENCE = m_model.createResource( "http://www.w3.org/ns/prov#Influence" );
    
    public static final Resource INSERTION = m_model.createResource( "http://www.w3.org/ns/prov#Insertion" );
    
    /** <p>An instantaneous event, or event for short, happens in the world and marks 
     *  a change in the world, in its activities and in its entities. The term 'event' 
     *  is commonly used in process algebra with a similar meaning. Events represent 
     *  communications or interactions; they are assumed to be atomic and instantaneous.</p>
     */
    public static final Resource INSTANTANEOUS_EVENT = m_model.createResource( "http://www.w3.org/ns/prov#InstantaneousEvent" );
    
    /** <p>An instance of prov:Invalidation provides additional descriptions about the 
     *  binary prov:wasInvalidatedBy relation from an invalidated prov:Entity to the 
     *  prov:Activity that invalidated it. For example, :uncracked_egg prov:wasInvalidatedBy 
     *  :baking; prov:qualifiedInvalidation [ a prov:Invalidation; prov:activity :baking; 
     *  :foo :bar ].</p>
     */
    public static final Resource INVALIDATION = m_model.createResource( "http://www.w3.org/ns/prov#Invalidation" );
    
    public static final Resource KEY_ENTITY_PAIR = m_model.createResource( "http://www.w3.org/ns/prov#KeyEntityPair" );
    
    public static final Resource LOCATION = m_model.createResource( "http://www.w3.org/ns/prov#Location" );
    
    public static final Resource MODIFY = m_model.createResource( "http://www.w3.org/ns/prov#Modify" );
    
    public static final Resource ORGANIZATION = m_model.createResource( "http://www.w3.org/ns/prov#Organization" );
    
    public static final Resource PERSON = m_model.createResource( "http://www.w3.org/ns/prov#Person" );
    
    /** <p>There exist no prescriptive requirement on the nature of plans, their representation, 
     *  the actions or steps they consist of, or their intended goals. Since plans 
     *  may evolve over time, it may become necessary to track their provenance, so 
     *  plans themselves are entities. Representing the plan explicitly in the provenance 
     *  can be useful for various tasks: for example, to validate the execution as 
     *  represented in the provenance record, to manage expectation failures, or to 
     *  provide explanations.</p>
     */
    public static final Resource PLAN = m_model.createResource( "http://www.w3.org/ns/prov#Plan" );
    
    /** <p>An instance of prov:PrimarySource provides additional descriptions about the 
     *  binary prov:hadPrimarySource relation from some secondary prov:Entity to an 
     *  earlier, primary prov:Entity. For example, :blog prov:hadPrimarySource :newsArticle; 
     *  prov:qualifiedPrimarySource [ a prov:PrimarySource; prov:entity :newsArticle; 
     *  :foo :bar ] .</p>
     */
    public static final Resource PRIMARY_SOURCE = m_model.createResource( "http://www.w3.org/ns/prov#PrimarySource" );
    
    public static final Resource PUBLISH = m_model.createResource( "http://www.w3.org/ns/prov#Publish" );
    
    public static final Resource PUBLISHER = m_model.createResource( "http://www.w3.org/ns/prov#Publisher" );
    
    /** <p>An instance of prov:Quotation provides additional descriptions about the binary 
     *  prov:wasQuotedFrom relation from some taken prov:Entity from an earlier, larger 
     *  prov:Entity. For example, :here_is_looking_at_you_kid prov:wasQuotedFrom :casablanca_script; 
     *  prov:qualifiedQuotation [ a prov:Quotation; prov:entity :casablanca_script; 
     *  :foo :bar ].</p>
     */
    public static final Resource QUOTATION = m_model.createResource( "http://www.w3.org/ns/prov#Quotation" );
    
    public static final Resource REMOVAL = m_model.createResource( "http://www.w3.org/ns/prov#Removal" );
    
    public static final Resource REPLACE = m_model.createResource( "http://www.w3.org/ns/prov#Replace" );
    
    /** <p>An instance of prov:Revision provides additional descriptions about the binary 
     *  prov:wasRevisionOf relation from some newer prov:Entity to an earlier prov:Entity. 
     *  For example, :draft_2 prov:wasRevisionOf :draft_1; prov:qualifiedRevision 
     *  [ a prov:Revision; prov:entity :draft_1; :foo :bar ].</p>
     */
    public static final Resource REVISION = m_model.createResource( "http://www.w3.org/ns/prov#Revision" );
    
    public static final Resource RIGHTS_ASSIGNMENT = m_model.createResource( "http://www.w3.org/ns/prov#RightsAssignment" );
    
    public static final Resource RIGHTS_HOLDER = m_model.createResource( "http://www.w3.org/ns/prov#RightsHolder" );
    
    public static final Resource ROLE = m_model.createResource( "http://www.w3.org/ns/prov#Role" );
    
    /** <p>Type for a generic provenance query service. Mainly for use in RDF provenance 
     *  query service descriptions, to facilitate discovery in linked data environments.</p>
     */
    public static final Resource SERVICE_DESCRIPTION = m_model.createResource( "http://www.w3.org/ns/prov#ServiceDescription" );
    
    public static final Resource SOFTWARE_AGENT = m_model.createResource( "http://www.w3.org/ns/prov#SoftwareAgent" );
    
    /** <p>An instance of prov:Start provides additional descriptions about the binary 
     *  prov:wasStartedBy relation from some started prov:Activity to an prov:Entity 
     *  that started it. For example, :foot_race prov:wasStartedBy :bang; prov:qualifiedStart 
     *  [ a prov:Start; prov:entity :bang; :foo :bar; prov:atTime '2012-03-09T08:05:08-05:00'^^xsd:dateTime 
     *  ] .</p>
     */
    public static final Resource START = m_model.createResource( "http://www.w3.org/ns/prov#Start" );
    
    public static final Resource SUBMIT = m_model.createResource( "http://www.w3.org/ns/prov#Submit" );
    
    /** <p>An instance of prov:Usage provides additional descriptions about the binary 
     *  prov:used relation from some prov:Activity to an prov:Entity that it used. 
     *  For example, :keynote prov:used :podium; prov:qualifiedUsage [ a prov:Usage; 
     *  prov:entity :podium; :foo :bar ].</p>
     */
    public static final Resource USAGE = m_model.createResource( "http://www.w3.org/ns/prov#Usage" );
    
}
